# Generated by Django 5.1.1 on 2024-10-03 12:08

import django.core.validators
import movies.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poster', models.ImageField(upload_to='posters')),
                ('title', models.CharField(max_length=256)),
                ('release_year', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1895), django.core.validators.MaxValueValidator(movies.models.next_year)])),
                ('description', models.CharField(max_length=2048)),
                ('rating', models.DecimalField(decimal_places=2, max_digits=4)),
                ('genre', models.CharField(choices=[('comedy', 'comedy'), ('drama', 'drama'), ('tragedy', 'tragedy'), ('cartoon', 'cartoon'), ('adventure', 'adventure')], max_length=32)),
            ],
            options={
                'verbose_name': 'movie',
                'verbose_name_plural': 'movies',
                'ordering': ['-rating'],
                'get_latest_by': 'release_year',
                'indexes': [models.Index(fields=['release_year', 'rating', 'genre'], name='movies_movi_release_829eac_idx')],
            },
        ),
    ]
